import {
  type CurrentFinding,
  type FindingMatchResult,
  fingerprintLLM,
  getLineContent,
  normaliseSnippet,
  type ResolvedFinding,
  type StoredFinding,
  type StoredReviewState,
} from "@src/features/pr/compare-state";
import type { Review } from "@src/features/pr/llm-call";
import type { ParsedFileDiff } from "@src/shared";
import stringSimilarity from "string-similarity";

const FUZZY_THRESHOLD = 0.7;

/**
 * Matches findings from the current run against findings from a previous run.
 * This is the core logic that allows the tool to track findings across commits,
 * identifying which are new, which are still active, and which have been fixed.
 *
 * @param staticFindings - Findings from the static security engine.
 * @param osvFindings - Findings from the dependency vulnerability scanner.
 * @param llmReviews - Findings generated by the LLM.
 * @param diffs - The parsed diffs for the current PR.
 * @param previous - The state from the previous run, loaded from the summary comment.
 * @returns An object containing lists of matched and fixed findings.
 */
export function matchFindings(
  llmReviews: Review[],
  diffs: ParsedFileDiff[],
  previous: StoredReviewState
): FindingMatchResult {
  const previousFindings = new Map<string, StoredFinding>(
    previous.findings.map((finding) => [finding.fingerprint, finding])
  );
  const matchedPrevious = new Set<string>();
  const matched: CurrentFinding[] = [];

  // Find a matching finding from the previous run.
  function findPrevious(fingerprint: string): StoredFinding | undefined {
    const finding = previousFindings.get(fingerprint);
    if (finding) {
      matchedPrevious.add(fingerprint);
    }
    return finding;
  }

  // Match LLM findings using exact and fuzzy matching.
  for (const review of llmReviews) {
    const lineContent = getLineContent(review.file, review.line, diffs);
    const fingerprint = fingerprintLLM(review.file, lineContent);
    const exactMatch = findPrevious(fingerprint);
    if (exactMatch) {
      matched.push({
        fingerprint,
        previous: exactMatch,
        review,
        source: "llm",
        status: "active",
      });
      continue;
    }

    const normalisedCurrentSnippet = normaliseSnippet(lineContent);

    let bestScore = 0;
    let bestMatch: StoredFinding | null = null;
    // Compare the current snippet against unmatched LLM findings from the previous run and keep the closest match.
    for (const [previousFingerprint, previousFinding] of previousFindings) {
      if (
        matchedPrevious.has(previousFingerprint) ||
        previousFinding.source !== "llm"
      ) {
        continue;
      }

      const prefix = `llm:${previousFinding.file}:`;
      const previousSnippet = previousFingerprint.startsWith(prefix)
        ? previousFingerprint.slice(prefix.length)
        : "";

      const score = stringSimilarity.compareTwoStrings(
        normalisedCurrentSnippet,
        previousSnippet
      );
      if (score > bestScore) {
        bestScore = score;
        bestMatch = previousFinding;
      }
    }

    // Treat highly similar snippets as the same finding.
    if (bestScore >= FUZZY_THRESHOLD && bestMatch) {
      matchedPrevious.add(bestMatch.fingerprint);
      matched.push({
        fingerprint,
        previous: bestMatch,
        review,
        source: "llm",
        status: "active",
      });
      continue;
    }
    matched.push({
      fingerprint,
      previous: null,
      review,
      source: "llm",
      status: "new",
    });
  }

  // Any previous finding that wasn't matched in this run is considered fixed.
  const fixed: ResolvedFinding[] = [];
  for (const [fingerprint, previousFinding] of previousFindings) {
    if (!matchedPrevious.has(fingerprint)) {
      fixed.push({
        previous: previousFinding,
      });
    }
  }

  return {
    fixed,
    matched,
  };
}
